name: howofhealthcare
favicon: null
layout_spectrum: 0.9296152391470969
typography_spectrum: 0.8794685993343592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5507558032404631
  lightness: 0.11334324697963893
  saturation: 0.257148644188419
  rhythmicContrast: 0.7711779836099595
purpose: []
